In [13]:
! pip install scikit-learn

In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [17]:
data = pd.read_csv('500hits.csv', encoding = 'latin-1')
data.head()

PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB  \
0       Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   
1   Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   
2  Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   
3   Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082   
4  Honus Wagner   21  2792  10430  1736  3430  640  252  101     0   963   

     SO   SB   CS     BA  HOF  
0   357  892  178  0.366    1  
1   696   78   31  0.331    1  
2   220  432  129  0.345    1  
3  1840  358   97  0.310    1  
4   327  722   15  0.329    1

In [36]:
df = data.drop(columns = ['PLAYER', 'CS'])
df.head()

YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA  \
0   24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366   
1   22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331   
2   22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345   
3   20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310   
4   21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329   

   HOF  
0    1  
1    1  
2    1  
3    1  
4    1

In [37]:
df['HOF'].unique()

array([1, 0, 2], dtype=int64)

In [38]:
df.shape

(465, 14)

In [39]:
df.isnull().sum().sum()

0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YRS     465 non-null    int64  
 1   G       465 non-null    int64  
 2   AB      465 non-null    int64  
 3   R       465 non-null    int64  
 4   H       465 non-null    int64  
 5   2B      465 non-null    int64  
 6   3B      465 non-null    int64  
 7   HR      465 non-null    int64  
 8   RBI     465 non-null    int64  
 9   BB      465 non-null    int64  
 10  SO      465 non-null    int64  
 11  SB      465 non-null    int64  
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 51.0 KB


In [42]:
df.describe().round(3)

YRS         G         AB         R         H       2B       3B  \
count  465.000   465.000    465.000   465.000   465.000  465.000  465.000   
mean    17.049  2048.699   7511.456  1150.314  2170.247  380.953   78.555   
std      2.765   354.392   1294.066   289.635   424.191   96.483   49.363   
min     11.000  1331.000   4981.000   601.000  1660.000  177.000    3.000   
25%     15.000  1802.000   6523.000   936.000  1838.000  312.000   41.000   
50%     17.000  1993.000   7241.000  1104.000  2076.000  366.000   67.000   
75%     19.000  2247.000   8180.000  1296.000  2375.000  436.000  107.000   
max     26.000  3308.000  12364.000  2295.000  4189.000  792.000  309.000   

            HR       RBI        BB        SO        SB       BA      HOF  
count  465.000   465.000   465.000   465.000   465.000  465.000  465.000  
mean   201.049   894.260   783.561   847.471   195.905    0.289    0.329  
std    143.623   486.193   327.432   489.224   181.846    0.021    0.475  
min      9.000     0.000   239.000     0.000     7.000    0.246    0.000  
25%     79.000   640.000   535.000   436.000    63.000    0.273    0.000  
50%    178.000   968.000   736.000   825.000   137.000    0.287    0.000  
75%    292.000  1206.000   955.000  1226.000   285.000    0.300    1.000  
max    755.000  2297.000  2190.000  2597.000  1406.000    0.366    2.000

In [54]:
X = df.iloc[: , 0:13]
y = df.iloc[:, 13]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.20, random_state = 42)

In [56]:
X_train.shape, y_train.shape

((372, 13), (372,))

In [57]:
X_test.shape, y_test.shape

((93, 13), (93,))

In [60]:
scaler = MinMaxScaler(feature_range = (0, 1, 2))
X_train = scaler.fit_transform(X_train)
X_train

array([[0.4       , 0.53009611, 0.52248984, ..., 0.43896804, 0.33333333,
        0.48214286],
       [0.26666667, 0.29792615, 0.1713581 , ..., 0.54948017, 0.15522175,
        0.03571429],
       [0.73333333, 0.55842185, 0.38813117, ..., 0.6542164 , 0.00786838,
        0.08928571],
       ...,
       [0.26666667, 0.21648963, 0.12840975, ..., 0.23450135, 0.05722461,
        0.41964286],
       [0.06666667, 0.12948912, 0.09445734, ..., 0.29688102, 0.04220315,
        0.28571429],
       [0.66666667, 0.52048558, 0.3562101 , ..., 0.74547555, 0.00643777,
        0.32142857]])

In [62]:
X_test= scaler.fit_transform(X_test)
X_test

array([[0.61538462, 0.5637111 , 0.42228421, ..., 0.36507102, 0.01825994,
        0.81196581],
       [0.61538462, 0.51908397, 0.54207345, ..., 0.17411888, 0.08807734,
        0.34188034],
       [0.84615385, 0.82090429, 0.6934759 , ..., 0.46344029, 0.08807734,
        0.47008547],
       ...,
       [0.30769231, 0.35819143, 0.306989  , ..., 0.84534456, 0.10418904,
        0.27350427],
       [0.53846154, 0.64650617, 0.69316597, ..., 0.6391373 , 0.08163265,
        0.58119658],
       [0.46153846, 0.30534351, 0.20316132, ..., 0.24302998, 0.03329753,
        0.30769231]])

In [69]:
knn = KNeighborsClassifier(n_neighbors = 8)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [78]:
y_pred = knn.predict(X_test)
print(y_pred,'Predct')

[1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0] Predct


In [77]:
knn.score(X_test, y_test)*100

87.09677419354838

In [83]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[62,  0],
       [12, 19]], dtype=int64)

In [86]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.84      1.00      0.91        62
           1       1.00      0.61      0.76        31

    accuracy                           0.87        93
   macro avg       0.92      0.81      0.84        93
weighted avg       0.89      0.87      0.86        93



In [87]:
print(knn.n_samples_fit_)

93


In [90]:
(0.93 + 0.82)* 2

3.5

In [91]:
0.93 + 0.82

1.75

In [93]:
3.5/1.75, 1.75/3.5

(2.0, 0.5)