In [1]:
import pandas as pd
import numpy as np

Series

In [2]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
obj2['d'] = 6

In [9]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

False

In [15]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [18]:
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [25]:
obj4.name = 'population'
obj4.index.name =  'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [26]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [27]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

DataFrame

In [28]:
data = {
    'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year' : [2000, 2001, 2002, 2001,  2002, 2003],
    'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
df = pd.DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [29]:
df.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [30]:
df.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [32]:
df2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'])
df2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [33]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [34]:
df2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [35]:
df2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [36]:
df2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [37]:
df2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [38]:
df2['debt'] =  16.5
df2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [39]:
df2['debt'] = np.arange(6.)
df2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [40]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
df2['debt'] = val
df2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [41]:
df2['eastern'] = df2['state'] == 'Ohio'
df2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [42]:
del df2['eastern']

In [43]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [44]:
populations = {
    'Ohio' : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6},
    'Nevada' : {2001 : 2.4, 2002 : 2.9}
}

In [45]:
df3 = pd.DataFrame(populations)
df3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [46]:
df3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [47]:
pd.DataFrame(populations, index = [2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [48]:
pdata = {
    'Ohio' : df3['Ohio'][:-1],
    'Nevada' : df3['Nevada'][:2]
}

In [49]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [50]:
df3.index.name = 'year'
df3.columns.name = 'state'
df3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [51]:
df3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [52]:
df2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

Index Objects

In [53]:
obj = pd.Series(np.arange(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [54]:
index[1:]

Index(['b', 'c'], dtype='object')

In [55]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [56]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [57]:
obj2.index is labels

True

In [58]:
df3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [59]:
df3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [60]:
'Ohio' in df3.columns

True

In [61]:
2003 in df3.index

False

In [62]:
pd.Index(['foo', 'foo', 'bar', 'bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

Reindexing

In [63]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [64]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [65]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [66]:
obj3.reindex(np.arange(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [67]:
df = pd.DataFrame(np.arange(9).reshape((3, 3)),
                  index = ['a', 'c', 'd'],
                  columns = ['Ohio', 'Texas', 'California'])
df

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [68]:
df2 = df.reindex(index = ['a', 'b', 'c', 'd'])
df2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [69]:
states = ['Texas', 'Utah', 'California']
df.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [70]:
df.reindex(states, axis = 'columns')

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [71]:
 df

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [72]:
df.loc[['a', 'd', 'c'], ['California', 'Texas']]

California  Texas
a           2      1
d           8      7
c           5      4

Dropping entries from an axis

In [73]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [74]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [75]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [76]:
df = pd.DataFrame(np.arange(16).reshape((4,4)),
                  index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns = ['one', 'two', 'three', 'four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [77]:
df.drop(index = ['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [78]:
df.drop(columns = ['two'])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [79]:
df.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [80]:
df.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

Indexing, Selection and Filtering

In [81]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [82]:
obj['b']

1.0

In [83]:
obj[1]

1.0

In [84]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [85]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [86]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [87]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [88]:
obj.loc[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [89]:
obj1 = pd.Series([1, 2, 3], index = [2, 0, 1])
obj2 = pd.Series([1, 2, 3], index = ['a', 'b', 'c'])

In [90]:
obj1

2    1
0    2
1    3
dtype: int64

In [91]:
obj2

a    1
b    2
c    3
dtype: int64

In [92]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [93]:
obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [94]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [95]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [96]:
obj2.loc['b' : 'c']

b    2
c    3
dtype: int64

In [97]:
obj2.loc['b' : 'c'] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [98]:
df = pd.DataFrame(np.arange(16).reshape((4,4)),
                  index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns = ['one', 'two', 'three', 'four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
df['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [100]:
df[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [101]:
df[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [102]:
df[df['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [103]:
df < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [104]:
df[df < 5] = 0
df

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Selection on DataFrame with loc and iloc

In [105]:
df

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
df.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [107]:
df.loc[['Colorado', 'New York']]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [108]:
df.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [109]:
df.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [110]:
df.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [111]:
df.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [112]:
df.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [113]:
df.iloc[:, :3] [df.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [114]:
df.loc[df.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Integer indexing pitfalls

In [115]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [116]:
# ser[-1] gives error

In [117]:
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])
ser2[-1]

2.0

In [118]:
ser.iloc[-1]

2.0

In [119]:
ser[:2]

0    0.0
1    1.0
dtype: float64

Pitfalls with chained indexing

In [120]:
df.loc[:, 'one'] = 1
df

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [121]:
df.iloc[2] = 5
df

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [122]:
df.loc[df['four'] > 5] = 3
df

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [123]:
df.loc[df.three == 5]['three'] = 6
df

<ipython-input-123-031e9fb16b2d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df.three == 5]['three'] = 6


one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [124]:
df.loc[df.three ==5, 'three'] = 6
df

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

Arithmetic and Data Alignment

In [125]:
s1 = pd.Series([7.3,  -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [126]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [127]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [128]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [129]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list('bcd'), index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [130]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [131]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [132]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [133]:
df1 = pd.DataFrame({'A' : [1, 2]})
df2 = pd.DataFrame({'B' : [3, 4]})

In [134]:
df1

A
0  1
1  2

In [135]:
df2

B
0  3
1  4

In [136]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

Arithmetic methods with fill values

In [137]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4,5),
                   columns = list('abcde'))

In [138]:
df2.loc[1, 'b'] = np.nan

In [139]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [140]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [141]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [142]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [143]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [144]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [145]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

Operations between DataFrame and Series

In [146]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [147]:
arr[0]

array([0., 1., 2., 3.])

In [148]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [149]:
df = pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = df.iloc[0]

In [150]:
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [151]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [152]:
df - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [153]:
series2 = pd.Series(np.arange(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [154]:
df + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [155]:
series3 = df['d']
df

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [156]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [157]:
df.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

Function Application and Mappping

In [158]:
df = pd.DataFrame(np.random.standard_normal((4,3)),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
df

b         d         e
Utah    0.288681  0.809356  0.595509
Ohio   -0.801573 -0.670701 -1.535207
Texas  -1.285534 -0.865542  0.088739
Oregon  0.202629  0.035076  0.953371

In [159]:
np.abs(df)

b         d         e
Utah    0.288681  0.809356  0.595509
Ohio    0.801573  0.670701  1.535207
Texas   1.285534  0.865542  0.088739
Oregon  0.202629  0.035076  0.953371

In [160]:
def f1(x):
  return x.max() - x.min()

In [161]:
df.apply(f1)

b    1.574216
d    1.674898
e    2.488578
dtype: float64

In [162]:
df.apply(f1, axis = 'columns')

Utah      0.520675
Ohio      0.864506
Texas     1.374273
Oregon    0.918295
dtype: float64

In [163]:
def f2(x):
  return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [164]:
df.apply(f2)

b         d         e
min -1.285534 -0.865542 -1.535207
max  0.288681  0.809356  0.953371

In [165]:
def my_format(x):
  return f"{x:.2f}"

In [166]:
df.applymap(my_format)

b      d      e
Utah     0.29   0.81   0.60
Ohio    -0.80  -0.67  -1.54
Texas   -1.29  -0.87   0.09
Oregon   0.20   0.04   0.95

In [167]:
df['e'].map(my_format)

Utah       0.60
Ohio      -1.54
Texas      0.09
Oregon     0.95
Name: e, dtype: object

Sorting and Ranking

In [168]:
obj = pd.Series(np.arange(4), index =  ['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [169]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [170]:
df = pd.DataFrame(np.arange(8).reshape((2,4)),
                  index = ['three', 'one'],
                  columns = ['d', 'a', 'b', 'c'])
df

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [171]:
df.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [172]:
df.sort_index(axis = 'columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [173]:
df.sort_index(axis = 'columns', ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [174]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [175]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [176]:
obj.sort_values(na_position = 'first')

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [177]:
df = pd.DataFrame({'b' : [4, 7, -3, 2], 'a' : [0, 1, 0, 1]})
df

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [178]:
df.sort_values('b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [179]:
df.sort_values(['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [180]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [181]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [182]:
obj.rank(ascending = False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [184]:
df = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a' : [0, 1, 0, 1], 'c' : [-2, 5, 8, -2.5]})
df

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [185]:
df.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [186]:
obj =pd.Series(np.arange(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [187]:
obj.index.is_unique

False

In [188]:
obj['a']

a    0
a    1
dtype: int64

In [189]:
obj['c']

4

In [191]:
df = pd.DataFrame(np.random.standard_normal((5,3)),
                  index = ['a', 'a', 'b', 'b', 'c'])
df

0         1         2
a  1.560003  0.189683  0.811537
a -1.394101  1.033126 -1.246778
b  0.891536  0.071582  1.810874
b -0.240739  2.231410  0.570019
c  0.303778  2.164213  1.822620

In [192]:
df.loc['b']

0         1         2
b  0.891536  0.071582  1.810874
b -0.240739  2.231410  0.570019

In [193]:
df.loc['c']

0    0.303778
1    2.164213
2    1.822620
Name: c, dtype: float64

In [195]:
df = pd.DataFrame([[1.44, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index = ['a', 'b', 'c', 'd'],
                  columns = ['one', 'two'])
df

one  two
a  1.44  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [196]:
df.sum()

one    9.29
two   -5.80
dtype: float64

In [197]:
df.sum(axis = 'columns')

a    1.44
b    2.60
c    0.00
d   -0.55
dtype: float64

In [198]:
df.sum(axis = 'index', skipna = False)

one   NaN
two   NaN
dtype: float64

In [199]:
df.sum(axis = 'columns', skipna = False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [200]:
df.mean(axis = 'columns')

a    1.440
b    1.300
c      NaN
d   -0.275
dtype: float64

In [202]:
df.idxmin()

one    d
two    b
dtype: object

In [203]:
df.idxmax()

one    b
two    d
dtype: object

In [204]:
df.cumsum()

one  two
a  1.44  NaN
b  8.54 -4.5
c   NaN  NaN
d  9.29 -5.8

In [205]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.096667 -2.900000
std    3.484112  2.262742
min    0.750000 -4.500000
25%    1.095000 -3.700000
50%    1.440000 -2.900000
75%    4.270000 -2.100000
max    7.100000 -1.300000

In [206]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [209]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [211]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [212]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [213]:
pd.value_counts(obj.to_numpy(), sort = False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [214]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [215]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [216]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [218]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [220]:
df = pd.DataFrame({'Qu1' : [1, 3, 4, 3, 4],
                     'Qu2' : [2, 3, 1, 2, 3],
                     'Qu3' : [1, 5, 2, 4, 4]
                     })
df

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [221]:
df['Qu1'].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [222]:
result = df.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [223]:
df = pd.DataFrame({'a' : [1, 1, 1, 2,2],
                   'b' : [0, 0, 1, 0, 0]})
df

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [224]:
df.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64