#  NumPy    (Numerical  Python)

In [5]:
# Installing Numpy Libary
pip install numpy    # (outside the Jupyter Notebook)

Unable to create process using 'C:\Users\Shekhani Laptop\anaconda3\python.exe "C:\Users\Shekhani Laptop\anaconda3\Scripts\pip-script.py" install numpy'


In [7]:
# Importing NumPy
     #To use NumPy in your Python scripts, you need to import it. The convention is to import it under the alias np.

'To use NumPy in your Python scripts, you need to import it. The convention is to import it under the alias np.'

In [8]:
import numpy as np

In [9]:
# The NumPy Array Object
     #The core of NumPy is the ndarray object, a fast and space-efficient multi-dimensional array that supports vectorized operations.
array = np.array([1, 2, 3, 4])
print(array)  # Output: [1 2 3 4]


[1 2 3 4]


# Creating NumPy Arrays

In [10]:
#You can create NumPy arrays from Python lists or tuples, and use various functions to generate arrays 
# filled with zeros, ones, or evenly spaced values.

In [61]:
# From list
arr1 = np.array(2)
print(arr1)
array = np.array([1, 2, 3, 4])
print(array)

2
[1 2 3 4]


In [62]:
# Zeros array
zeros_array = np.zeros((3, 3))

In [63]:
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [65]:
# Ones array
ones_array = np.ones((2, 2))

print(ones_array)

[[1. 1.]
 [1. 1.]]


In [67]:
# Evenly spaced values
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


# Task 1: Creating and Manipulating Arrays


In [57]:
# Task: Create different types of arrays and perform basic operations.
# Instructions:
# Create an array of zeros with shape (3, 3).
# Create an array of ones with shape (2, 4).
# Create an array with values from 10 to 50, with a step of 10.
# Add 5 to each element of the array created in step 3.

In [80]:
import numpy as np
arra1 = np.linspace(10, 50, 10)
print(arra1)

[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556 50.        ]


In [81]:
arra2 = np.linspace(10, 50, 10)+5
print(arra2)

[15.         19.44444444 23.88888889 28.33333333 32.77777778 37.22222222
 41.66666667 46.11111111 50.55555556 55.        ]


# Array Data Types

In [16]:
#NumPy arrays are homogeneous, meaning all elements in an array must be of the same data type. 
#You can specify the data type using the dtype parameter.

In [18]:
float_array = np.array([1, 2, 3], dtype=float)
print(float_array.dtype)  # Output: float64
print(float_array)

float64
[1. 2. 3.]


# Basic Array Operations

In [19]:
# NumPy supports element-wise operations, meaning operations are applied to each element in the array independently.

In [20]:
# Creating two differnt arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [21]:
# Addition
sum_array = array1 + array2

In [22]:
# Multiplication
prod_array = array1 * array2


In [82]:
# Broadcasting
# NumPy automatically expands the smaller array's dimensions to match the larger array's shape without actually copying the data. 
#This process is known as broadcasting.
broadcast_array = array1 + 10

In [83]:
print(broadcast_array)

[11 12 13]


# Indexing and Slicing
Like lists, NumPy arrays can be indexed and sliced to access specific elements or subarrays. Advanced indexing allows you to access arrays in more sophisticated ways.

In [84]:
array = np.array([10, 20, 30, 40, 50])

# Indexing
print(array[2])  # Output: 30

# Slicing
print(array[1:4])  # Output: [20 30 40]

# Advanced Indexing
print(array[[0, 2, 4]])  # Output: [10 30 50]


30
[20 30 40]
[10 30 50]


# Task 3: Indexing and Slicing


In [ ]:
# Task: Practice indexing and slicing arrays.
# Instructions:
# Create an array [10, 20, 30, 40, 50, 60].
# Slice the array to get the first three elements.
# Slice the array to get the last three elements.
# Use advanced indexing to get the elements at indices 1, 3, and 5.

# Array Shape and Reshape

In [42]:
# The shape of a NumPy array can be accessed and modified using the .shape attribute and the reshape() function.

In [44]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Shape
print("Shape of Array")
print(array.shape)  # Output: (2, 3)

# Reshape
reshaped_array = array.reshape((3, 2))
print("Re-Shape of Array")
print(reshaped_array)

Shape of Array
(2, 3)
Re-Shape of Array
[[1 2]
 [3 4]
 [5 6]]


# Task 4: Array Shape and Reshape
<!-- Task: Reshape arrays and explore different shapes.
Instructions:
Create an array with values from 1 to 12.
Reshape it into a 3x4 matrix.
Reshape the same array into a 2x6 matrix.
Flatten the reshaped 3x4 matrix back into a 1D array. -->

In [58]:
# Task 4: Array Shape and Reshape
# Task: Reshape arrays and explore different shapes.
# Instructions:
# Create an array with values from 1 to 12.
# Reshape it into a 3x4 matrix.
# Reshape the same array into a 2x6 matrix.
# Flatten the reshaped 3x4 matrix back into a 1D array.

# Array Manipulation

In [47]:
array = np.array([1, 2, 3, 4, 5])

# Sum
total_sum = np.sum(array)

# Mean
mean_value = np.mean(array)
print(mean_value)
# Standard Deviation
std_dev = np.std(array)
print(std_dev)


3.0
1.4142135623730951


# Task 6: Mathematical Operations

In [ ]:
# Task: Perform mathematical operations on arrays.
# Instructions:
# Create an array [10, 20, 30, 40, 50].
# Calculate the sum of all elements.
# Calculate the mean of the array.
# Find the standard deviation.

# Linear Algebra with NumPy
NumPy includes a submodule for linear algebra operations such as matrix multiplication, transposition, and finding eigenvalues.

In [52]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)
# Transpose
transposed = np.transpose(matrix)
print(transposed)

# Matrix Multiplication
result = np.dot(matrix, transposed)
print(result)

# [[1*1 + 2*2, 1*3 + 2*4],  ->  [[ 5, 11],
# [3*1 + 4*2, 3*3 + 4*4]]       [11, 25]]



[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]


# Linear Algebra Operations


In [ ]:
# Task: Perform linear algebra operations using NumPy.
# Instructions:
# Create a 2x2 matrix [[1, 2], [3, 4]].
# Calculate its transpose.
# Perform matrix multiplication of the matrix with its transpose.
# Find the determinant of the matrix.

# Random Number Generation
NumPy’s random module allows you to generate random numbers, random arrays, and draw samples from statistical distributions.


In [54]:
# Random Array
random_array = np.random.random((2, 3))
print(random_array)
# Normal Distribution
normal_array = np.random.normal(0, 1, 1000)
print(normal_array)


[[0.30740541 0.51008081 0.67782818]
 [0.64197525 0.86595513 0.87938425]]
[ 4.39731111e-01 -1.63386996e+00  6.03831201e-02 -6.75486865e-01
 -3.10445455e-01  6.80763155e-01 -9.69905209e-02  6.74167484e-01
 -4.83960598e-01 -4.13383580e-02  9.68911718e-01 -9.22505228e-01
  6.13058226e-01  5.66820318e-01  7.68442522e-01 -1.21954877e-01
 -6.54393318e-01  7.39349473e-01 -1.56001082e+00  2.70757407e+00
  1.78425801e+00 -7.77588041e-01 -2.07222989e-01 -3.57780548e-01
  1.12627183e+00 -1.62369461e-01  4.83737598e-01  7.04573981e-04
  3.31959450e-01  3.27428261e-01 -1.63578731e+00 -3.06409059e-01
  2.64838148e-02 -1.39133423e+00 -1.06232051e-01  3.81496405e-01
  6.62495132e-01  2.90631478e-02  1.58709265e+00 -1.17004361e+00
  1.92517757e+00 -6.70435954e-01  1.06347571e+00  7.65575031e-01
  6.17581854e-01 -1.33479723e+00 -4.83017334e-01  6.83116522e-01
 -1.12396939e+00  7.66810569e-01  1.01817364e+00 -1.13399899e-01
  1.73770253e+00  1.36619385e+00 -2.45347860e-01 -5.87095535e-01
 -9.20712188e-01 

# Random Number Generation

In [ ]:
# Task: Generate random numbers and analyze the distribution.
# Instructions:
# Generate a random array of shape (2, 3) with values between 0 and 1.
# Generate a random array of 1000 elements following a normal distribution with mean 0 and standard deviation 1.
# Plot the histogram of the normal distribution.


# Advanced Indexing Techniques
Advanced indexing includes boolean indexing and fancy indexing, which allow you to filter and select elements based on specific conditions.

In [55]:
array = np.array([1, 2, 3, 4, 5, 6])

# Boolean Indexing
bool_idx = array > 3
filtered_array = array[bool_idx]
print(filtered_array)
# Fancy Indexing
fancy_array = array[[0, 2, 4]]
print(fancy_array)


[4 5 6]
[1 3 5]


# Performance Optimization

In [56]:
large_array = np.random.random(1000000)

# Vectorized Operation
sum_of_squares = np.sum(large_array ** 2)
print(sum_of_squares)

333522.7161438503
